=== Johnny-Wubrg/mtg-dungeon-crawler/src/assets/dungeons/_schema.json
{
	"title": "JSON Schema for dungeon definitions",
	"$schema": "http://json-schema.org/draft-07/schema",
	"type": "object",
	"properties": {
		"name": {
			"type": "string",
			"description": "The name of the dungeon"
		},
		"slug": {
			"type": "string",
			"description": "The slug/identifier of the dungeon"
		},
		"entrances": {
			"type": "array",
      "description": "The ids of the rooms the user can start in",
			"minimum": 1,
      "items": { "type": "number" }
		},
		"rooms": {
      "type": "array",
      "description": "The rooms in the dungeon",
			"minimum": 1,
      "items": { "$ref": "#/definitions/room" }
		}
	},
	"required": ["name", "entrances", "rooms"],
	"definitions": {
		"room": {
			"type": "object",
			"properties": {
				"id": {
					"type": "number",
					"description": "A unique identifier for the room"
				},
				"name": {
					"type": "string",
					"description": "The name of the room"
				},
				"effect": {
					"type": "string",
					"description": "The effect that triggers when the player ventures into the room"
				},
				"exits": {
					"type": "array",
					"description": "The ids of rooms the player can venture to",
					"items": { "type": "number" }
				}
			},
			"required": ["name", "effect", "exits"]
		}
	}
}

=== Johnny-Wubrg/mtg-dungeon-crawler/src/assets/dungeons/lost-mine-of-phandelver.dungeon.json
{
	"name": "Lost Mine of Phandelver",
	"slug": "lost-mine-of-phandelver",
  "entrances": [1],
	"rooms": [
		{
			"id": 1,
			"name": "Cave Entrance",
			"effect": "Scry 1.",
			"exits": [2, 3]
		},
		{
			"id": 2,
			"name": "Goblin Lair",
			"effect": "Create a 1/1 red Goblin creature token.",
			"exits": [4, 5]
		},
		{
			"id": 3,
			"name": "Mine Tunnels",
			"effect": "Create a Treasure token.",
			"exits": [5, 6]
		},
		{
			"id": 4,
			"name": "Storeroom",
			"effect": "Put a +1/+1 counter on target creature.",
			"exits": [7]
		},
		{
			"id": 5,
			"name": "Dark Pool",
			"effect": "Each opponent loses 1 life and you gain 1 life.",
			"exits": [7]
		},
		{
			"id": 6,
			"name": "Fungi Cavern",
			"effect": "Target creature gets -4/-0 until your next turn.",
			"exits": [7]
		},
		{
			"id": 7,
			"name": "Temple of Dumathoin",
			"effect": "Draw a card.",
			"exits": []
		}
	]
}
